/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Dell
 */
public class bmiCalcu extends javax.swing.JFrame {

    /**
     * Creates new form bmiCalcu
     */
    public bmiCalcu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        heightTitle = new javax.swing.JLabel();
        weightTitle = new javax.swing.JLabel();
        heightFill = new javax.swing.JTextField();
        weightFill = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bmiResult = new javax.swing.JLabel();
        bmiButton = new javax.swing.JButton();
        healthIndi = new javax.swing.JLabel();
        saran = new javax.swing.JLabel();
        nextButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        heightTitle.setBackground(new java.awt.Color(153, 153, 255));
        heightTitle.setFont(new java.awt.Font("Quosm", 1, 18)); // NOI18N
        heightTitle.setForeground(new java.awt.Color(255, 255, 255));
        heightTitle.setText("ENTER YOUR HEIGHT");
        jPanel1.add(heightTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 210, 25));

        weightTitle.setBackground(new java.awt.Color(153, 153, 255));
        weightTitle.setFont(new java.awt.Font("Quosm", 1, 18)); // NOI18N
        weightTitle.setForeground(new java.awt.Color(255, 255, 255));
        weightTitle.setText("ENTER YOUR WEIGHT");
        jPanel1.add(weightTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 200, 25));

        heightFill.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        heightFill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heightFillActionPerformed(evt);
            }
        });
        jPanel1.add(heightFill, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 170, 90, -1));

        weightFill.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        weightFill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weightFillActionPerformed(evt);
            }
        });
        jPanel1.add(weightFill, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 220, 90, -1));

        jLabel1.setFont(new java.awt.Font("Quosm", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("cm");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, -1, -1));

        jLabel2.setFont(new java.awt.Font("Quosm", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("kg");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 230, -1, -1));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("DIN", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Are you on a healthy weight?");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 410, 70));

        bmiResult.setFont(new java.awt.Font("Quosm", 0, 48)); // NOI18N
        bmiResult.setForeground(new java.awt.Color(255, 255, 255));
        bmiResult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(bmiResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 172, 62));

        bmiButton.setBackground(new java.awt.Color(255, 255, 255));
        bmiButton.setFont(new java.awt.Font("DIN Alternate Light", 1, 18)); // NOI18N
        bmiButton.setText("YOUR BMI IS");
        bmiButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bmiButtonMouseClicked(evt);
            }
        });
        bmiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmiButtonActionPerformed(evt);
            }
        });
        jPanel1.add(bmiButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 172, 40));

        healthIndi.setFont(new java.awt.Font("Quosm", 1, 18)); // NOI18N
        healthIndi.setForeground(new java.awt.Color(255, 255, 255));
        healthIndi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(healthIndi, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, 230, 40));

        saran.setFont(new java.awt.Font("Quosm", 1, 12)); // NOI18N
        saran.setForeground(new java.awt.Color(255, 255, 255));
        saran.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(saran, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 590, 40));

        nextButton.setBackground(new java.awt.Color(255, 255, 255));
        nextButton.setFont(new java.awt.Font("Segoe Script", 0, 18)); // NOI18N
        nextButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/arrow kecil bgt kanan.png"))); // NOI18N
        nextButton.setContentAreaFilled(false);
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });
        jPanel1.add(nextButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 431, 50, 50));

        backButton.setBackground(new java.awt.Color(255, 255, 255));
        backButton.setFont(new java.awt.Font("Segoe Script", 0, 18)); // NOI18N
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/arrow kecil bgt kiri.png"))); // NOI18N
        backButton.setContentAreaFilled(false);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        jPanel1.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 50, 36));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/rsz_1rsz_1rsz_logo.png"))); // NOI18N
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 77));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/tq background2.jpg"))); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void weightFillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weightFillActionPerformed

    }//GEN-LAST:event_weightFillActionPerformed

    private void bmiButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bmiButtonMouseClicked

        double height = Double.parseDouble(heightFill.getText());
        double weight = Double.parseDouble(weightFill.getText());
        double bmi = (weight / ((height / 10)*(height / 10))) * 100;
        int value = (int)bmi;
        String bmiresult = String.valueOf(value);
        bmiResult.setText(bmiresult);

        if (bmi < 18.5) {
            healthIndi.setText("You're underweight.");
            saran.setText("Konsumsi makanan dan minuman yg jumlah kalori > dari kebutuhan kalori harian Anda.");
        }
        else if ( bmi >= 18.5 && bmi <=24.9 ) {
            healthIndi.setText("You're healthy.");
            saran.setText("Konsumsi makanan dan minuman sesuai dengan kebutuhan kalori harian Anda.");
        }
        else if ( bmi >= 25 && bmi <= 29.999 ) {
            healthIndi.setText("You're overweight.");
            saran.setText("Konsumsi makanan dan minuman yg jumlah kalori < dari kebutuhan kalori harian Anda.");
        }
        else {
            healthIndi.setText("You're obese.");
            saran.setText("Konsumsi makanan dan minuman yg jumlah kalori < dari kebutuhan kalori harian Anda.");
        }
    }//GEN-LAST:event_bmiButtonMouseClicked

    private void bmiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmiButtonActionPerformed

    }//GEN-LAST:event_bmiButtonActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        this.setVisible(false);
        loadingSplash splash = new loadingSplash();
        splash.animation();
    }//GEN-LAST:event_nextButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.setVisible(false);
        yourBodyTypes_frame back = new yourBodyTypes_frame();
        back.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void heightFillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heightFillActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_heightFillActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bmiCalcu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new bmiCalcu().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel background;
    private javax.swing.JButton bmiButton;
    private javax.swing.JLabel bmiResult;
    private javax.swing.JLabel healthIndi;
    private javax.swing.JTextField heightFill;
    private javax.swing.JLabel heightTitle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logo;
    private javax.swing.JButton nextButton;
    private javax.swing.JLabel saran;
    private javax.swing.JTextField weightFill;
    private javax.swing.JLabel weightTitle;
    // End of variables declaration//GEN-END:variables
}
