/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.Timer;

/**
 *
 * @author Dell
 */
public class loadingPage_frame extends javax.swing.JFrame {
    int counter = 0;
    Timer tm;
    /**
     * Creates new form yourAge_frame
     */
    public loadingPage_frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        counterLoad = new javax.swing.JLabel();
        percent = new javax.swing.JLabel();
        workButton = new javax.swing.JButton();
        tips = new javax.swing.JLabel();
        logo1 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        counterLoad.setFont(new java.awt.Font("Quosm SemiBold", 1, 48)); // NOI18N
        counterLoad.setForeground(new java.awt.Color(255, 255, 255));
        counterLoad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        counterLoad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/fitness gede.png"))); // NOI18N
        counterLoad.setText("LOADING");
        jPanel1.add(counterLoad, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 330, 70));

        percent.setFont(new java.awt.Font("Quosm SemiBold", 1, 45)); // NOI18N
        percent.setForeground(new java.awt.Color(255, 255, 255));
        percent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        percent.setText("99%");
        jPanel1.add(percent, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 180, 60));

        workButton.setBackground(new java.awt.Color(40, 41, 115));
        workButton.setFont(new java.awt.Font("Quosm SemiBold", 0, 18)); // NOI18N
        workButton.setForeground(new java.awt.Color(255, 255, 255));
        workButton.setText("show my workout routine!");
        workButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        workButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                workButtonMouseClicked(evt);
            }
        });
        jPanel1.add(workButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, -1, 50));

        tips.setFont(new java.awt.Font("Quosm SemiBold", 1, 18)); // NOI18N
        tips.setForeground(new java.awt.Color(255, 255, 255));
        tips.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tips.setText("*press the title of the workout to find out the benefits!*");
        jPanel1.add(tips, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 500, -1));

        logo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/rsz_1rsz_1rsz_logo.png"))); // NOI18N
        jPanel1.add(logo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 77));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/tq background2.jpg"))); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 750, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 447, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void workButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_workButtonMouseClicked

        int age = DataTransfer.getAge();
        int bodyTpe = DataTransfer.getBodyTypes();
        String gender = DataTransfer.getGender();
        System.out.println(gender);
        
        this.setVisible(false);
        if(gender.equals("female") && bodyTpe == 1 ) {
            this.setVisible(false);
            olahragaSatu_frame next = new olahragaSatu_frame();
            next.setVisible(true);
            
        }else if (gender.equals("female") && bodyTpe == 2) {
            this.setVisible(false);
            olahragaDua_frame next = new olahragaDua_frame();
            next.setVisible(true);
            
        }else if (gender.equals("female") && bodyTpe == 3) {
            this.setVisible(false);
            olahragaTiga_frame next = new olahragaTiga_frame();
            next.setVisible(true);
            
        }else if (gender.equals("male") && bodyTpe == 1) {
            this.setVisible(false);
            olahragaEmpat_frame next = new olahragaEmpat_frame();
            next.setVisible(true);
            
        }else if (gender.equals("male") && bodyTpe == 2) {
            this.setVisible(false);
            olahragaLima_frame next = new olahragaLima_frame();
            next.setVisible(true);
            
        }else if (gender.equals("male") && bodyTpe == 3) {
            this.setVisible(false);
            olahragaEnam_frame next = new olahragaEnam_frame();
            next.setVisible(true);                
    }//GEN-LAST:event_workButtonMouseClicked

    /**
     * @param args the command line arguments
     *
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loadingPage_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            
            loadingPage_frame sp = new loadingPage_frame();
            sp.setVisible(true);

           
        });
        
       
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel counterLoad;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logo1;
    public javax.swing.JLabel percent;
    public javax.swing.JLabel tips;
    public javax.swing.JButton workButton;
    // End of variables declaration//GEN-END:variables
}


