/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class olahragaDua_frame extends javax.swing.JFrame {

    /**
     * Creates new form olahragaSatu
     */
    public olahragaDua_frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane7 = new javax.swing.JTabbedPane();
        monday = new javax.swing.JPanel();
        lsitpic = new javax.swing.JLabel();
        apupic = new javax.swing.JLabel();
        rpupic = new javax.swing.JLabel();
        dpupic = new javax.swing.JLabel();
        kpupic = new javax.swing.JLabel();
        kpubutton = new javax.swing.JButton();
        dipsbutton = new javax.swing.JButton();
        rpubutton = new javax.swing.JButton();
        apubutton = new javax.swing.JButton();
        dpubutton = new javax.swing.JButton();
        lsitbutton = new javax.swing.JButton();
        dipspic = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        tuesday = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        legraisebutton = new javax.swing.JButton();
        bcbutton = new javax.swing.JButton();
        ktbutton = new javax.swing.JButton();
        rtbutton = new javax.swing.JButton();
        situpbutton = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        background2 = new javax.swing.JLabel();
        wednesday = new javax.swing.JPanel();
        jnpubutton = new javax.swing.JButton();
        cubutton = new javax.swing.JButton();
        pubutton = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        background4 = new javax.swing.JLabel();
        thursday = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        pukabutton = new javax.swing.JButton();
        tkbbutton = new javax.swing.JButton();
        stpubutton = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        background3 = new javax.swing.JLabel();
        friday = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lungesbutton = new javax.swing.JButton();
        ssbutton = new javax.swing.JButton();
        jsbutton = new javax.swing.JButton();
        psbutton = new javax.swing.JButton();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        background5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        monday.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lsitpic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lsitpic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/ezgif.com-resize (1).gif"))); // NOI18N
        lsitpic.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        monday.add(lsitpic, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, 170));

        apupic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        apupic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/archer push up.gif"))); // NOI18N
        apupic.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        monday.add(apupic, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, -1, 180));

        rpupic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rpupic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/regular push up close.gif"))); // NOI18N
        rpupic.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        monday.add(rpupic, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 200, 180));

        dpupic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dpupic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/diamond push up.gif"))); // NOI18N
        dpupic.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        monday.add(dpupic, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 320, -1, 110));

        kpupic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kpupic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/knee pushup.gif"))); // NOI18N
        kpupic.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        kpupic.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        monday.add(kpupic, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, -1, 170));

        kpubutton.setFont(new java.awt.Font("DIN Alternate Light", 1, 18)); // NOI18N
        kpubutton.setForeground(new java.awt.Color(255, 255, 255));
        kpubutton.setText("KNEE PUSH UP");
        kpubutton.setContentAreaFilled(false);
        kpubutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kpubutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kpubuttonActionPerformed(evt);
            }
        });
        monday.add(kpubutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, -1, 30));

        dipsbutton.setFont(new java.awt.Font("DIN Alternate Light", 1, 18)); // NOI18N
        dipsbutton.setForeground(new java.awt.Color(255, 255, 255));
        dipsbutton.setText("DIPS");
        dipsbutton.setContentAreaFilled(false);
        dipsbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dipsbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dipsbuttonActionPerformed(evt);
            }
        });
        monday.add(dipsbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));

        rpubutton.setFont(new java.awt.Font("DIN Alternate Light", 1, 18)); // NOI18N
        rpubutton.setForeground(new java.awt.Color(255, 255, 255));
        rpubutton.setText("REGULAR PUSH UP");
        rpubutton.setContentAreaFilled(false);
        rpubutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rpubutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rpubuttonActionPerformed(evt);
            }
        });
        monday.add(rpubutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, -1, -1));

        apubutton.setFont(new java.awt.Font("DIN Alternate Light", 1, 18)); // NOI18N
        apubutton.setForeground(new java.awt.Color(255, 255, 255));
        apubutton.setText("ARCHER PUSH UP");
        apubutton.setContentAreaFilled(false);
        apubutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        apubutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apubuttonActionPerformed(evt);
            }
        });
        monday.add(apubutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 440, -1, -1));

        dpubutton.setFont(new java.awt.Font("DIN Alternate Light", 1, 18)); // NOI18N
        dpubutton.setForeground(new java.awt.Color(255, 255, 255));
        dpubutton.setText("DIAMOND PUSH UP");
        dpubutton.setContentAreaFilled(false);
        dpubutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dpubutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dpubuttonActionPerformed(evt);
            }
        });
        monday.add(dpubutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 440, -1, -1));

        lsitbutton.setFont(new java.awt.Font("DIN Alternate Light", 1, 18)); // NOI18N
        lsitbutton.setForeground(new java.awt.Color(255, 255, 255));
        lsitbutton.setText("L SIT");
        lsitbutton.setContentAreaFilled(false);
        lsitbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lsitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lsitbuttonActionPerformed(evt);
            }
        });
        monday.add(lsitbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, -1, -1));

        dipspic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/DIPSS.gif"))); // NOI18N
        dipspic.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        monday.add(dipspic, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 150, 160));

        jLabel4.setFont(new java.awt.Font("Quosm SemiBold", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("8x");
        monday.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, -1, 20));

        jLabel22.setFont(new java.awt.Font("Quosm SemiBold", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("8x");
        monday.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 220, -1, 20));

        jLabel23.setFont(new java.awt.Font("Quosm SemiBold", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("8x");
        monday.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 460, -1, 20));

        jLabel24.setFont(new java.awt.Font("Quosm SemiBold", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("8x");
        monday.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 460, -1, 20));

        jLabel25.setFont(new java.awt.Font("Quosm SemiBold", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("8x");
        monday.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 460, -1, 20));

        jLabel26.setFont(new java.awt.Font("Quosm SemiBold", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("8x");
        monday.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, -1, 20));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/tq background2.jpg"))); // NOI18N
        monday.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 1, 750, 500));

        jTabbedPane7.addTab("MONDAY", monday);

        tuesday.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/bicycle crunches.gif"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tuesday.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 40, 200, -1));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/sit up 1.gif"))); // NOI18N
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tuesday.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/knee touch.gif"))); // NOI18N
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tuesday.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, -1, 140));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/russian twist.gif"))); // NOI18N
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tuesday.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, -1, -1));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/leg raise.gif"))); // NOI18N
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tuesday.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 42, -1, 200));

        legraisebutton.setFont(new java.awt.Font("DIN Alternate Light", 1, 18)); // NOI18N
        legraisebutton.setForeground(new java.awt.Color(255, 255, 255));
        legraisebutton.setText("LEG RAISE");
        legraisebutton.setContentAreaFilled(false);
        legraisebutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        legraisebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                legraisebuttonActionPerformed(evt);
            }
        });
        tuesday.add(legraisebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, -1, -1));

        bcbutton.setFont(new java.awt.Font("DIN Alternate Light", 1, 18)); // NOI18N
        bcbutton.setForeground(new java.awt.Color(255, 255, 255));
        bcbutton.setText("BICYCLE CRUNCHES");
        bcbutton.setContentAreaFilled(false);
        bcbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bcbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcbuttonActionPerformed(evt);
            }
        });
        tuesday.add(bcbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, -1, -1));

        ktbutton.setFont(new java.awt.Font("DIN Alternate Light", 1, 18)); // NOI18N
        ktbutton.setForeground(new java.awt.Color(255, 255, 255));
        ktbutton.setText("KNEE TOUCH");
        ktbutton.setContentAreaFilled(false);
        ktbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ktbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ktbuttonActionPerformed(evt);
            }
        });
        tuesday.add(ktbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 460, -1, -1));

        rtbutton.setFont(new java.awt.Font("DIN Alternate Light", 1, 18)); // NOI18N
        rtbutton.setForeground(new java.awt.Color(255, 255, 255));
        rtbutton.setText("RUSSIAN TWIST");
        rtbutton.setContentAreaFilled(false);
        rtbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rtbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rtbuttonActionPerformed(evt);
            }
        });
        tuesday.add(rtbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 460, -1, -1));

        situpbutton.setFont(new java.awt.Font("DIN Alternate Light", 1, 18)); // NOI18N
        situpbutton.setForeground(new java.awt.Color(255, 255, 255));
        situpbutton.setText("SIT UP");
        situpbutton.setContentAreaFilled(false);
        situpbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        situpbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                situpbuttonActionPerformed(evt);
            }
        });
        tuesday.add(situpbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, -1, -1));

        jLabel27.setFont(new java.awt.Font("Quosm SemiBold", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("8x");
        tuesday.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, -1, 20));

        jLabel28.setFont(new java.awt.Font("Quosm SemiBold", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("8x");
        tuesday.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, -1, 20));

        jLabel29.setFont(new java.awt.Font("Quosm SemiBold", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("8x");
        tuesday.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 270, -1, 20));

        jLabel30.setFont(new java.awt.Font("Quosm SemiBold", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("8x");
        tuesday.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 480, -1, 20));

        jLabel31.setFont(new java.awt.Font("Quosm SemiBold", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("8x");
        tuesday.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 480, -1, 20));

        background2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/tq background2.jpg"))); // NOI18N
        tuesday.add(background2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 750, 520));

        jTabbedPane7.addTab("TUESDAY", tuesday);

        wednesday.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jnpubutton.setFont(new java.awt.Font("DIN Alternate Light", 1, 18)); // NOI18N
        jnpubutton.setForeground(new java.awt.Color(255, 255, 255));
        jnpubutton.setText("JUMP NEGATIVE PULL UP");
        jnpubutton.setContentAreaFilled(false);
        jnpubutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jnpubutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnpubuttonActionPerformed(evt);
            }
        });
        wednesday.add(jnpubutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, -1, -1));

        cubutton.setFont(new java.awt.Font("DIN Alternate Light", 1, 18)); // NOI18N
        cubutton.setForeground(new java.awt.Color(255, 255, 255));
        cubutton.setText("CHIN UP");
        cubutton.setContentAreaFilled(false);
        cubutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cubutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cubuttonActionPerformed(evt);
            }
        });
        wednesday.add(cubutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 250, -1, -1));

        pubutton.setFont(new java.awt.Font("DIN Alternate Light", 1, 18)); // NOI18N
        pubutton.setForeground(new java.awt.Color(255, 255, 255));
        pubutton.setText("PULL UP");
        pubutton.setContentAreaFilled(false);
        pubutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pubutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pubuttonActionPerformed(evt);
            }
        });
        wednesday.add(pubutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pull up.gif"))); // NOI18N
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        wednesday.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 200, -1));

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/jump negative push up.gif"))); // NOI18N
        jLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        wednesday.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 150, -1));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/chin up.gif"))); // NOI18N
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        wednesday.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 40, 200, -1));

        jLabel33.setFont(new java.awt.Font("Quosm SemiBold", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("8x");
        wednesday.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, -1, 20));

        jLabel34.setFont(new java.awt.Font("Quosm SemiBold", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("8x");
        wednesday.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, -1, 20));

        jLabel35.setFont(new java.awt.Font("Quosm SemiBold", 1, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("8x");
        wednesday.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 270, -1, 20));

        background4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/tq background2.jpg"))); // NOI18N
        wednesday.add(background4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 750, 540));

        jTabbedPane7.addTab("WEDNESDAY", wednesday);

        thursday.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/shoulder touch push up.gif"))); // NOI18N
        jLabel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        thursday.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/push up kaki atas.gif"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        thursday.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, -1, -1));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/tangan ke bawah.gif"))); // NOI18N
        jLabel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        thursday.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 200, 120));

        pukabutton.setFont(new java.awt.Font("DIN Alternate Light", 1, 18)); // NOI18N
        pukabutton.setForeground(new java.awt.Color(255, 255, 255));
        pukabutton.setText("PUSH UP KAKI ATAS");
        pukabutton.setContentAreaFilled(false);
        pukabutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pukabutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pukabuttonActionPerformed(evt);
            }
        });
        thursday.add(pukabutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, -1, -1));

        tkbbutton.setFont(new java.awt.Font("DIN Alternate Light", 1, 18)); // NOI18N
        tkbbutton.setForeground(new java.awt.Color(255, 255, 255));
        tkbbutton.setText("TANGAN KE BAWAH");
        tkbbutton.setContentAreaFilled(false);
        tkbbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tkbbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tkbbuttonActionPerformed(evt);
            }
        });
        thursday.add(tkbbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 440, -1, -1));

        stpubutton.setFont(new java.awt.Font("DIN Alternate Light", 1, 18)); // NOI18N
        stpubutton.setForeground(new java.awt.Color(255, 255, 255));
        stpubutton.setText("SHOULDER TOUCH PUSH UP");
        stpubutton.setContentAreaFilled(false);
        stpubutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        stpubutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stpubuttonActionPerformed(evt);
            }
        });
        thursday.add(stpubutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        jLabel32.setFont(new java.awt.Font("Quosm SemiBold", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("8x");
        thursday.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, -1, 20));

        jLabel38.setFont(new java.awt.Font("Quosm SemiBold", 1, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("8x");
        thursday.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, -1, 20));

        jLabel39.setFont(new java.awt.Font("Quosm SemiBold", 1, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("8x");
        thursday.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 460, -1, 20));

        background3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/tq background2.jpg"))); // NOI18N
        thursday.add(background3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 510));

        jTabbedPane7.addTab("THURSDAY", thursday);

        friday.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pistol squad (2).gif"))); // NOI18N
        jLabel1.setText("foto olahraga 3");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        friday.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 310, 185, -1));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/lunges.gif"))); // NOI18N
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        friday.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, 186));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/squad silang.gif"))); // NOI18N
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        friday.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, -1, -1));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/jump squat.gif"))); // NOI18N
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        friday.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 210, 110));

        lungesbutton.setFont(new java.awt.Font("DIN Alternate Light", 1, 18)); // NOI18N
        lungesbutton.setForeground(new java.awt.Color(255, 255, 255));
        lungesbutton.setText("LUNGES");
        lungesbutton.setContentAreaFilled(false);
        lungesbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lungesbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lungesbuttonActionPerformed(evt);
            }
        });
        friday.add(lungesbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, -1, -1));

        ssbutton.setFont(new java.awt.Font("DIN Alternate Light", 1, 18)); // NOI18N
        ssbutton.setForeground(new java.awt.Color(255, 255, 255));
        ssbutton.setText("SQUAT SILANG");
        ssbutton.setContentAreaFilled(false);
        ssbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ssbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ssbuttonActionPerformed(evt);
            }
        });
        friday.add(ssbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, -1, -1));

        jsbutton.setFont(new java.awt.Font("DIN Alternate Light", 1, 18)); // NOI18N
        jsbutton.setForeground(new java.awt.Color(255, 255, 255));
        jsbutton.setText("JUMP SQUAT");
        jsbutton.setContentAreaFilled(false);
        jsbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jsbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsbuttonActionPerformed(evt);
            }
        });
        friday.add(jsbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, -1, -1));

        psbutton.setFont(new java.awt.Font("DIN Alternate Light", 1, 18)); // NOI18N
        psbutton.setForeground(new java.awt.Color(255, 255, 255));
        psbutton.setText("PISTOL SQUAT");
        psbutton.setContentAreaFilled(false);
        psbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        psbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psbuttonActionPerformed(evt);
            }
        });
        friday.add(psbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 430, -1, -1));

        jLabel40.setFont(new java.awt.Font("Quosm SemiBold", 1, 14)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("8x");
        friday.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, -1, 20));

        jLabel41.setFont(new java.awt.Font("Quosm SemiBold", 1, 14)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("8x");
        friday.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 260, -1, 20));

        jLabel42.setFont(new java.awt.Font("Quosm SemiBold", 1, 14)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("8x");
        friday.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 450, -1, 20));

        jLabel43.setFont(new java.awt.Font("Quosm SemiBold", 1, 14)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("8x");
        friday.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 450, -1, 20));

        background5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/tq background2.jpg"))); // NOI18N
        friday.add(background5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 510));

        jTabbedPane7.addTab("FRIDAY", friday);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane7)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kpubuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kpubuttonActionPerformed
        JOptionPane.showMessageDialog(null, "MANFAAT = akan mengenai otot bagian dada bawah (pectoralis major) serta mengenai otot tricep dan juga bicep, bahu juga kadang ikut berkontraksi.");
    }//GEN-LAST:event_kpubuttonActionPerformed

    private void rpubuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rpubuttonActionPerformed
        JOptionPane.showMessageDialog(null, "MANFAAT = akan mengenai otot bagian dada bawah (pectoralis major) serta mengenai otot tricep dan juga bicep, bahu juga kadang ikut berkontraksi abs juga dapat ikut.");
    }//GEN-LAST:event_rpubuttonActionPerformed

    private void apubuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apubuttonActionPerformed
        JOptionPane.showMessageDialog(null, "MANFAAT = akan mengenai otot bagian dada samping dan depan yang dimana tricep dan bicep juga bermain saat ini, shoulder pun ikut kena.");
    }//GEN-LAST:event_apubuttonActionPerformed

    private void dpubuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dpubuttonActionPerformed
        JOptionPane.showMessageDialog(null, "MANFAAT = akan mengenai otot dada tengah dan juga focus mengenai tricep.");
    }//GEN-LAST:event_dpubuttonActionPerformed

    private void lsitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lsitbuttonActionPerformed
        JOptionPane.showMessageDialog(null, "MANFAAT = akan mengenai otot abs dan dada samping dan juga menguatkan grip kita, dan mengenai otot shoulder. ");
    }//GEN-LAST:event_lsitbuttonActionPerformed

    private void situpbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_situpbuttonActionPerformed
        JOptionPane.showMessageDialog(null, "MANFAAT = akan mengenai otot abs bagian atas.");
    }//GEN-LAST:event_situpbuttonActionPerformed

    private void pubuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pubuttonActionPerformed
        JOptionPane.showMessageDialog(null, "MANFAAT = akan mengenai otot bagian lengan, menguatkan grip kita, dan juga akan memainkan otot bagian punggung dan juga sayap samping.");
    }//GEN-LAST:event_pubuttonActionPerformed

    private void cubuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cubuttonActionPerformed
        JOptionPane.showMessageDialog(null, "MANFAAT = akan menguatkan otot lengan dan juga dada bagian atas dan juga otot bahu dan punggung. ");
    }//GEN-LAST:event_cubuttonActionPerformed

    private void jnpubuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnpubuttonActionPerformed
       JOptionPane.showMessageDialog(null, "MANFAAT = digunakan untuk latihan bila seseorang belum bisa pull up atau sedang mengumpulkan tenaga ");
    }//GEN-LAST:event_jnpubuttonActionPerformed

    private void stpubuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stpubuttonActionPerformed
        JOptionPane.showMessageDialog(null, "MANFAAT = untuk melatih ketahanan bahu bagian depan dan juga tricep, dan dalam hal ini otot abs juga bekerja.");
    }//GEN-LAST:event_stpubuttonActionPerformed

    private void tkbbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tkbbuttonActionPerformed
        JOptionPane.showMessageDialog(null, "MANFAAT = akan mengenai otot bahu secara full dan juga tricep.");
    }//GEN-LAST:event_tkbbuttonActionPerformed

    private void pukabuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pukabuttonActionPerformed
        JOptionPane.showMessageDialog(null, "MANFAAT = untuk menguatkan lebih dalam shoulder dikarenakan dalam posisi itu shoulder akan bekerja dengan maksimal dibantu dengan pectoralis minor / dada bagian atas. ");
    }//GEN-LAST:event_pukabuttonActionPerformed

    private void lungesbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lungesbuttonActionPerformed
        JOptionPane.showMessageDialog(null, "MANFAAT = untuk memacu peningkatan mobilitas sendi, kekuatan, fleksibiltas, core, dan sistem kardiovaskular.");
    }//GEN-LAST:event_lungesbuttonActionPerformed

    private void ssbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ssbuttonActionPerformed
        JOptionPane.showMessageDialog(null, "MANFAAT = untuk mengencangkan otot paha, serta menguatkan badan bagian bawah.");
    }//GEN-LAST:event_ssbuttonActionPerformed

    private void jsbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsbuttonActionPerformed
        JOptionPane.showMessageDialog(null, "MANFAAT = untuk membantu mengencangkan otot paha dan bokong.");
    }//GEN-LAST:event_jsbuttonActionPerformed

    private void psbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psbuttonActionPerformed
        JOptionPane.showMessageDialog(null, "MANFAAT = berfungsi untuk otot paha yang dimana berguna untuk membuat lebih strong dari keseimbangan kaki kita");
    }//GEN-LAST:event_psbuttonActionPerformed

    private void rtbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rtbuttonActionPerformed
        JOptionPane.showMessageDialog(null, "MANFAAT = akan mengenai otot bagian tengah dan samping");
    }//GEN-LAST:event_rtbuttonActionPerformed

    private void ktbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ktbuttonActionPerformed
        JOptionPane.showMessageDialog(null, "MANFAAT = akan mengenai otot bagian paling samping yang berguna untuk membuat diri kita semakin ramping. ");
    }//GEN-LAST:event_ktbuttonActionPerformed

    private void bcbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcbuttonActionPerformed
        JOptionPane.showMessageDialog(null, "MANFAAT = akan sangat mengenai otot abs bagian bawah yang dimana sangat berpengaruh dengan kaki juga.");
    }//GEN-LAST:event_bcbuttonActionPerformed

    private void legraisebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_legraisebuttonActionPerformed
        JOptionPane.showMessageDialog(null, "MANFAAT = akan mengenai otot abs bagian bawah dan juga mengencangkan otot bagian kaki atas / paha.");
    }//GEN-LAST:event_legraisebuttonActionPerformed

    private void dipsbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dipsbuttonActionPerformed
        JOptionPane.showMessageDialog(null, "MANFAAT = menguatkan grip juga sama seperti l seat namun dalam dips untuk kontraksi otot dada dan tricep lebih besar dibanding dips l seat");
    }//GEN-LAST:event_dipsbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(olahragaDua_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(olahragaDua_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(olahragaDua_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(olahragaDua_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new olahragaDua_frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton apubutton;
    private javax.swing.JLabel apupic;
    private javax.swing.JLabel background;
    private javax.swing.JLabel background2;
    private javax.swing.JLabel background3;
    private javax.swing.JLabel background4;
    private javax.swing.JLabel background5;
    private javax.swing.JButton bcbutton;
    private javax.swing.JButton cubutton;
    private javax.swing.JButton dipsbutton;
    private javax.swing.JLabel dipspic;
    private javax.swing.JButton dpubutton;
    private javax.swing.JLabel dpupic;
    private javax.swing.JPanel friday;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTabbedPane jTabbedPane7;
    private javax.swing.JButton jnpubutton;
    private javax.swing.JButton jsbutton;
    private javax.swing.JButton kpubutton;
    private javax.swing.JLabel kpupic;
    private javax.swing.JButton ktbutton;
    private javax.swing.JButton legraisebutton;
    private javax.swing.JButton lsitbutton;
    private javax.swing.JLabel lsitpic;
    private javax.swing.JButton lungesbutton;
    private javax.swing.JPanel monday;
    private javax.swing.JButton psbutton;
    private javax.swing.JButton pubutton;
    private javax.swing.JButton pukabutton;
    private javax.swing.JButton rpubutton;
    private javax.swing.JLabel rpupic;
    private javax.swing.JButton rtbutton;
    private javax.swing.JButton situpbutton;
    private javax.swing.JButton ssbutton;
    private javax.swing.JButton stpubutton;
    private javax.swing.JPanel thursday;
    private javax.swing.JButton tkbbutton;
    private javax.swing.JPanel tuesday;
    private javax.swing.JPanel wednesday;
    // End of variables declaration//GEN-END:variables
}
