/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Dell
 */
public class welcomePage extends javax.swing.JFrame {

    /**
     * Creates new form welcomePage
     */
    public welcomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        workButton = new javax.swing.JButton();
        titleSatu = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        pic = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        workButton.setBackground(new java.awt.Color(40, 41, 115));
        workButton.setFont(new java.awt.Font("Quosm SemiBold", 0, 18)); // NOI18N
        workButton.setForeground(new java.awt.Color(255, 255, 255));
        workButton.setText("start working out");
        workButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        workButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                workButtonMouseClicked(evt);
            }
        });
        workButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workButtonActionPerformed(evt);
            }
        });
        jPanel1.add(workButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, -1, 43));

        titleSatu.setFont(new java.awt.Font("DIN Black", 1, 24)); // NOI18N
        titleSatu.setForeground(new java.awt.Color(255, 255, 255));
        titleSatu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleSatu.setText("make yourself stronger than your excuses.");
        titleSatu.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel1.add(titleSatu, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 570, 77));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/rsz_1rsz_1rsz_logo.png"))); // NOI18N
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 77));

        pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/strong (1).png"))); // NOI18N
        jPanel1.add(pic, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 460, 390));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/tq background2.jpg"))); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 704, 449));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void workButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workButtonActionPerformed

    }//GEN-LAST:event_workButtonActionPerformed

    private void workButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_workButtonMouseClicked
        this.setVisible(false);
        yourName_frame s = new yourName_frame();
        s.setVisible(true);
    }//GEN-LAST:event_workButtonMouseClicked


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(welcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(welcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(welcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(welcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new welcomePage().setVisible(true);
        });
    }
    public static String nameTrainer;
    public static int age;
    public static String gender;
    public static int bodytypes;
    public static int genderr = 0;

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel pic;
    private javax.swing.JLabel titleSatu;
    private javax.swing.JButton workButton;
    // End of variables declaration//GEN-END:variables
}
