/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import GUI.DataTransfer;
import static GUI.DataTransfer.gender;
import static GUI.welcomePage.genderr;
import javax.swing.JOptionPane;
/**
 *
 * @author Dell
 */
public class yourGender_frame extends javax.swing.JFrame {

    /**
     * Creates new form yourGender_frame
     */
    public yourGender_frame() {
        initComponents();

        buttonGroup1.add(female);
        buttonGroup1.add(male);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        question = new javax.swing.JLabel();
        nextButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        female = new javax.swing.JButton();
        male = new javax.swing.JButton();
        hiTrainer = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("DIN Black", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("LET US KNOW MORE ABOUT YOU.");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 620, 70));

        question.setBackground(new java.awt.Color(153, 153, 255));
        question.setFont(new java.awt.Font("Quosm SemiBold", 0, 24)); // NOI18N
        question.setForeground(new java.awt.Color(255, 255, 255));
        question.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        question.setText("what are you?");
        jPanel1.add(question, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 379, 32));

        nextButton.setBackground(new java.awt.Color(255, 255, 255));
        nextButton.setFont(new java.awt.Font("Segoe Script", 0, 18)); // NOI18N
        nextButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/arrow kecil bgt kanan.png"))); // NOI18N
        nextButton.setContentAreaFilled(false);
        nextButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });
        jPanel1.add(nextButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 441, 50, 50));

        backButton.setBackground(new java.awt.Color(255, 255, 255));
        backButton.setFont(new java.awt.Font("Segoe Script", 0, 18)); // NOI18N
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/arrow kecil bgt kiri.png"))); // NOI18N
        backButton.setContentAreaFilled(false);
        backButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        jPanel1.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 50, 50));

        female.setBackground(new java.awt.Color(255, 255, 255));
        female.setFont(new java.awt.Font("Quosm", 1, 14)); // NOI18N
        female.setForeground(new java.awt.Color(243, 107, 36));
        female.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/female kecil (1).png"))); // NOI18N
        buttonGroup1.add(female);
        female.setContentAreaFilled(false);
        female.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });
        jPanel1.add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 250, 170));

        male.setBackground(new java.awt.Color(255, 255, 255));
        male.setFont(new java.awt.Font("Quosm", 1, 14)); // NOI18N
        male.setForeground(new java.awt.Color(243, 107, 36));
        male.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/male keci; (1).png"))); // NOI18N
        buttonGroup1.add(male);
        male.setContentAreaFilled(false);
        male.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });
        jPanel1.add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 190, 190));

        hiTrainer.setFont(new java.awt.Font("Quosm", 1, 24)); // NOI18N
        hiTrainer.setForeground(new java.awt.Color(255, 255, 255));
        hiTrainer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(hiTrainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, 450, 34));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/rsz_1rsz_1rsz_logo.png"))); // NOI18N
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 77));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/tq background2.jpg"))); // NOI18N
        background.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -2, 760, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 745, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.setVisible(false);
        yourAge_frame back = new yourAge_frame();
        back.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
        DataTransfer.setGender("male");
        genderr = 1;
        hiTrainer.setText("Male, noted!");
    }//GEN-LAST:event_maleActionPerformed

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
        DataTransfer.setGender("female");
        genderr = 2;
        hiTrainer.setText("Female, noted!");
    }//GEN-LAST:event_femaleActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed

        if (genderr == 0) {
            this.setVisible(true);
            JOptionPane.showMessageDialog(null, "Please choose one!", "Inane error", JOptionPane.ERROR_MESSAGE);
        } else if ( genderr == 1 || genderr == 2) {
            this.setVisible(false);
            yourBodyTypes_frame next = new yourBodyTypes_frame();
            next.setVisible(true);
        }
    }//GEN-LAST:event_nextButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(yourGender_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new yourGender_frame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel background;
    private javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JButton female;
    private javax.swing.JLabel hiTrainer;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logo;
    public javax.swing.JButton male;
    private javax.swing.JButton nextButton;
    private javax.swing.JLabel question;
    // End of variables declaration//GEN-END:variables

    private static class aboveTwen {

        public aboveTwen() {
        }
    }
}
