/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import GUI.DataTransfer;
import static GUI.DataTransfer.age;
import javax.swing.JOptionPane;
/**
 *
 * @author Dell
 */
public class yourAge_frame extends javax.swing.JFrame {

    /**
     * Creates new form yourAge_frame
     */
    public yourAge_frame() {
        initComponents();
        
        int age = 0;
        buttonGroup1.add(belowSe);
        buttonGroup1.add(inBetween);
        buttonGroup1.add(aboveTwen);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        hiTrainer = new javax.swing.JLabel();
        nextButton = new javax.swing.JButton();
        aboveTwen = new javax.swing.JRadioButton();
        belowSe = new javax.swing.JRadioButton();
        inBetween = new javax.swing.JRadioButton();
        backButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        question = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("DIN Black", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("LET US KNOW MORE ABOUT YOU.");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 620, 70));

        hiTrainer.setFont(new java.awt.Font("Quosm SemiBold", 1, 18)); // NOI18N
        hiTrainer.setForeground(new java.awt.Color(255, 255, 255));
        hiTrainer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(hiTrainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 368, 34));

        nextButton.setBackground(new java.awt.Color(255, 255, 255));
        nextButton.setFont(new java.awt.Font("Segoe Script", 0, 18)); // NOI18N
        nextButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/arrow kecil bgt kanan.png"))); // NOI18N
        nextButton.setContentAreaFilled(false);
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });
        jPanel1.add(nextButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 400, 50, -1));

        aboveTwen.setBackground(new java.awt.Color(243, 107, 37));
        aboveTwen.setFont(new java.awt.Font("Quosm SemiBold", 1, 18)); // NOI18N
        aboveTwen.setForeground(new java.awt.Color(255, 255, 255));
        aboveTwen.setText("above 20");
        aboveTwen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboveTwenActionPerformed(evt);
            }
        });
        jPanel1.add(aboveTwen, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, 120, 43));

        belowSe.setBackground(new java.awt.Color(45, 45, 114));
        belowSe.setFont(new java.awt.Font("Quosm SemiBold", 1, 18)); // NOI18N
        belowSe.setForeground(new java.awt.Color(255, 255, 255));
        belowSe.setText("below 17");
        belowSe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                belowSeActionPerformed(evt);
            }
        });
        jPanel1.add(belowSe, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 101, 43));

        inBetween.setBackground(new java.awt.Color(243, 107, 37));
        inBetween.setFont(new java.awt.Font("Quosm SemiBold", 1, 18)); // NOI18N
        inBetween.setForeground(new java.awt.Color(255, 255, 255));
        inBetween.setText("17 - 20");
        inBetween.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inBetweenActionPerformed(evt);
            }
        });
        jPanel1.add(inBetween, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 101, 43));

        backButton.setBackground(new java.awt.Color(255, 255, 255));
        backButton.setFont(new java.awt.Font("Segoe Script", 0, 18)); // NOI18N
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/arrow kecil bgt kiri.png"))); // NOI18N
        backButton.setContentAreaFilled(false);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        jPanel1.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 50, 36));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        question.setBackground(new java.awt.Color(153, 153, 255));
        question.setFont(new java.awt.Font("Quosm SemiBold", 0, 24)); // NOI18N
        question.setForeground(new java.awt.Color(255, 255, 255));
        question.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        question.setText("how old are you?");
        jPanel1.add(question, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 379, 32));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/rsz_1rsz_1rsz_logo.png"))); // NOI18N
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 77));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/tq background2.jpg"))); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 750, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 447, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.setVisible(false);
        yourName_frame back = new yourName_frame();
        back.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void inBetweenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inBetweenActionPerformed
        if(inBetween.isSelected()) {
            belowSe.setSelected(false);
            aboveTwen.setSelected(false);
        }
        int age = 17;
        hiTrainer.setText("Noted.");
        
        DataTransfer.setAge(17);
    }//GEN-LAST:event_inBetweenActionPerformed

    private void belowSeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_belowSeActionPerformed
        if(belowSe.isSelected()) {
            inBetween.setSelected(false);
            aboveTwen.setSelected(false);
        }
        
        int age = 16;
        hiTrainer.setText("Noted. You're still young.");
        
        DataTransfer.setAge(16);
    }//GEN-LAST:event_belowSeActionPerformed

    private void aboveTwenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboveTwenActionPerformed

        if(aboveTwen.isSelected()) {
            inBetween.setSelected(false);
            belowSe.setSelected(false);
        }
        int age = 20;
        hiTrainer.setText("Noted. You're above 20 years old.");
        
        DataTransfer.setAge(20);
    }//GEN-LAST:event_aboveTwenActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed

        if ( age == 0 ) {
            this.setVisible(true);
            JOptionPane.showMessageDialog(null, "Please choose one!", "Inane error", JOptionPane.ERROR_MESSAGE);
        } else {
           this.setVisible(false);
           yourGender_frame next = new yourGender_frame();
           next.setVisible(true); 
        }
    }//GEN-LAST:event_nextButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(yourAge_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new yourAge_frame().setVisible(true);
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton aboveTwen;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel background;
    private javax.swing.JRadioButton belowSe;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel hiTrainer;
    private javax.swing.JRadioButton inBetween;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logo;
    private javax.swing.JButton nextButton;
    private javax.swing.JLabel question;
    // End of variables declaration//GEN-END:variables
}
